-- Coffee Analysis

/* 1. Coffee consumer
How many people in each city are estimated to consume coffee, 
given that 25% of the population does?
*/

with coffee_consumed(city,coffee_consumers,population) as
(
select cit.city_name,
	   count(cus.customer_name),
	   cit.population
from city cit
join customers cus
on cit.city_id = cus.city_id
group by cit.city_name, cit.population
)
select *, (coffee_consumers/population)*1000000 as percent
from coffee_consumed
order by coffee_consumers desc
;

select city_name,
	   round((population * 0.25)/1000000,2) as consumers_in_millions
from city
order by 2 desc
;

-- 2. Total revenue

select *
from sales;

select sum(total) as revenue
from sales;

/*
2. What is the total revenue generated from coffee sales 
across all cities in the last quarter of 2023?
*/

select sum(total) as revenue_2023
from sales
where year(sale_date) = '2023'
and quarter(sale_date) = '4'
;

/*
Revenue generated by each city
*/

select c.city_name,sum(s.total) as revenue
from sales s
join customers cus
on s.customer_id = cus.customer_id
join city c
on cus.city_id = c.city_id
group by c.city_name
order by 2 desc
;

/*
3. Sales Count for Each Product
How many units of each coffee product have been sold?
*/

select p.product_name,
	   count(s.sale_id) as quantity_sold,
       sum(s.total) as total_sales
from products p 
join sales s
on p.product_id = s.product_id
group by p.product_name
order by 2 desc
;

/*
4. Average Sales Amount per City
What is the average sales amount per customer in each city?
*/

with avg_customer_sale as
(
select c.city_name,
	   count(distinct cus.customer_id) as number_of_customers,
	   sum(s.total) as sales_in_millions
from city c
join customers cus
on c.city_id = cus.city_id
join sales s
on s.customer_id = cus.customer_id
group by c.city_name
order by 3 desc
)
select *, 
	   round((sales_in_millions/number_of_customers),2) as avg_sales
from avg_customer_sale
;

/*
5. City Population and Coffee Consumers
Provide a list of cities along with their 
populations and estimated coffee consumers.
*/

with cnt_customer(id,customer) as
(
select city_id, count(customer_name)
from customers
group by city_id
),
population(id,city,consumers_in_millions) as
(
select city_id,city_name,round((population*0.25)/1000000,2)
from city
)
select p.*,c.customer
from cnt_customer c
join population p
on c.id = p.id
;

/*
6. Top Selling Products by City
What are the top 3 selling products in each city 
based on sales volume?
*/

with top_city(city,product,qty_sold) as
(
select ci.city_name,
	   p.product_name,
       count(s.sale_id)
from sales s
join products p
on s.product_id = p.product_id
join customers c
on c.customer_id = s.customer_id
join city ci
on ci.city_id = c.city_id
group by ci.city_name,
		 p.product_name
),
ranking_city as
(
select *,
	   dense_rank() over(partition by city order by qty_sold desc) as ranking
from top_city
order by city
)
select *
from ranking_city
where ranking <= 3
;

/*
7. Customer Segmentation by City
How many unique customers are there in each city 
who have purchased coffee products?
*/


select ci.city_name,
	   count(distinct c.customer_id) as num_of_customers
from city ci
join customers c
on ci.city_id = c.city_id
join sales s
on c.customer_id = s.customer_id
join products p
on s.product_id = p.product_id
where p.product_id between 1 and 14
group by ci.city_name
;

/*
8. Average Sale vs Rent
Find each city and their average sale per customer 
and avg rent per customer
*/


with sale_rent(city,rent,customers,sales) as
(
select ci.city_name,
       ci.estimated_rent,
       count(distinct c.customer_id),
       sum(s.total)
from city ci
join customers c
on ci.city_id = c.city_id
join sales s
on c.customer_id = s.customer_id
group by ci.city_name,ci.estimated_rent
)
select city,customers,
		round(rent/customers,2) as avg_rent,
        round(sales/customers,2) as avg_sales
from sale_rent
order by 1
;

/*
9. Monthly Sales Growth
Sales growth rate: Calculate the percentage growth (or decline) 
in sales over different time periods (monthly). for each city
*/

with previous_sale as
(
select ci.city_id,
	   ci.city_name,
	   month(s.sale_date)  as months,
       year(s.sale_date) as years,
       sum(s.total) as sales
from city ci
join customers c
on ci.city_id = c.city_id
join sales s
on c.customer_id = s.customer_id
group by ci.city_id,
		 ci.city_name,
	     month(s.sale_date),
         year(s.sale_date)
),
current_sale as
(
select *,
       lag((sales),1) over(partition by city_name order by years,months) as sales2
from previous_sale
)
select city_name,months,
	   (sales-sales2)/sales2*100 as growth_ratio
from current_sale
;

/*
10. Market Potential Analysis
Identify top 3 city based on highest sales, return city name, total sale, 
total rent, total customers, estimated coffee consumer
*/

with top_city(city,sales,rent,num_of_customers,est_population) as
(
select ci.city_name,
	   sum(s.total) as sales,
       ci.estimated_rent,
       count(distinct c.customer_id),
       (ci.population * 0.25)
from city ci
join customers c
on ci.city_id = c.city_id
join sales s
on c.customer_id = s.customer_id
join products p
group by ci.city_name,
		 ci.estimated_rent,
         (ci.population * 0.25)
),
rank_city as
(
select *,
	   dense_rank() over(order by sales desc) as num
from top_city
)
select city,
	   num_of_customers,
	   round(sales/num_of_customers,2) as avg_sales,
       round(rent/num_of_customers,2) as avg_rent,
       round(est_population/1000000,2) as population_in_millions
from rank_city
where num <= 5
;
